local function seg(ax, az, bx, bz) return { a = { x = ax, z = az }, b = { x = bx, z = bz } } end

describe("Geom.segmentsIntersect", function()
  it("crossing segments intersect", function()
    assert_true(Geom.segmentsIntersect(seg(0, 0, 2, 2), seg(0, 2, 2, 0)))
  end)
  it("parallel segments do not intersect", function()
    assert_false(Geom.segmentsIntersect(seg(0, 0, 2, 0), seg(0, 1, 2, 1)))
  end)
  it("collinear overlapping segments intersect", function()
    assert_true(Geom.segmentsIntersect(seg(0, 0, 2, 0), seg(1, 0, 3, 0)))
  end)
  it("collinear disjoint segments do not intersect", function()
    assert_false(Geom.segmentsIntersect(seg(0, 0, 1, 0), seg(2, 0, 3, 0)))
  end)
  it("segments touching at an endpoint intersect", function()
    assert_true(Geom.segmentsIntersect(seg(0, 0, 1, 1), seg(1, 1, 2, 0)))
  end)
  it("T-junction intersects", function()
    assert_true(Geom.segmentsIntersect(seg(0, 0, 2, 0), seg(1, 0, 1, 2)))
  end)
  it("near miss does not intersect", function()
    assert_false(Geom.segmentsIntersect(seg(0, 0, 1, 1), seg(1.1, 1.1, 2, 0)))
  end)
end)

describe("Geom.tilePath", function()
  local origin = { x = 0, z = 0, heading = 0 }

  it("straight from origin heading 0 ends at (0, length)", function()
    local segs, exit = Geom.tilePath("straight", 3, origin)
    assert_eq(#segs, 1)
    assert_near(exit.x, 0)
    assert_near(exit.z, Config.tiles[3].straight)
    assert_near(exit.heading, 0)
  end)
  it("straight at heading 90 goes toward +x", function()
    local _, exit = Geom.tilePath("straight", 2, { x = 1, z = 1, heading = 90 })
    assert_near(exit.x, 1 + Config.tiles[2].straight)
    assert_near(exit.z, 1)
  end)
  it("heading +z: left curve bends toward -x, right toward +x; heading changes by sweep", function()
    local _, l = Geom.tilePath("left", 3, origin)
    local _, r = Geom.tilePath("right", 3, origin)
    assert_true(l.x < 0, "left should go -x")
    assert_true(r.x > 0, "right should go +x")
    assert_true(l.z > 0 and r.z > 0)
    assert_near(r.heading, Config.tiles[3].soft.sweep)
    assert_near(l.heading, 360 - Config.tiles[3].soft.sweep)
  end)
  it("mirror symmetry: left and right exits mirror in x", function()
    local _, l = Geom.tilePath("left", 4, origin)
    local _, r = Geom.tilePath("right", 4, origin)
    assert_near(l.x, -r.x)
    assert_near(l.z, r.z)
  end)
  it("curve exit matches circular-arc closed form", function()
    local t = Config.tiles[2].soft
    local th = t.sweep * math.pi / 180
    local _, r = Geom.tilePath("right", 2, origin)
    assert_near(r.x, t.radius * (1 - math.cos(th)))
    assert_near(r.z, t.radius * math.sin(th))
  end)
  it("curve produces Config.arcSegments contiguous segments", function()
    local segs = Geom.tilePath("left", 3, origin)
    assert_eq(#segs, Config.arcSegments)
    for i = 2, #segs do
      assert_near(segs[i].a.x, segs[i - 1].b.x)
      assert_near(segs[i].a.z, segs[i - 1].b.z)
    end
  end)
  it("all points of an arc lie on the circle", function()
    local t = Config.tiles[3].soft
    local segs = Geom.tilePath("right", 3, origin)
    for _, s in ipairs(segs) do
      local d = math.sqrt((s.b.x - t.radius) ^ 2 + s.b.z ^ 2)
      assert_near(d, t.radius, 1e-9)
    end
  end)
  it("exit pose of tile N equals entry pose of tile N+1", function()
    local s1, e1 = Geom.tilePath("right", 3, origin)
    local s2 = Geom.tilePath("straight", 2, e1)
    assert_near(s2[1].a.x, e1.x)
    assert_near(s2[1].a.z, e1.z)
    assert_near(s1[#s1].b.x, e1.x)
  end)
  it("eight right curves of 45 degrees return heading to start", function()
    local pose = origin
    for _ = 1, 8 do local _, e = Geom.tilePath("right", 1, pose); pose = e end
    assert_near(pose.heading % 360, 0)
    assert_near(pose.x, 0, 1e-9)
    assert_near(pose.z, 0, 1e-9)
  end)
end)

describe("Geom.pathHitsTrails", function()
  local origin = { x = 0, z = 0, heading = 0 }
  it("ignores the joint with the mover's own previous tile", function()
    local s1, e1 = Geom.tilePath("straight", 3, origin)
    local s2 = Geom.tilePath("right", 3, e1)
    assert_false(Geom.pathHitsTrails(s2, { { owner = "Red", segs = s1 } }, { x = e1.x, z = e1.z }))
  end)
  it("without the ignore joint the touching joint counts as a hit", function()
    local s1, e1 = Geom.tilePath("straight", 3, origin)
    local s2 = Geom.tilePath("right", 3, e1)
    assert_true(Geom.pathHitsTrails(s2, { { owner = "Red", segs = s1 } }, nil))
  end)
  it("detects crossing an opponent trail", function()
    local s = Geom.tilePath("straight", 3, origin)
    assert_true(Geom.pathHitsTrails(s, { { owner = "Blue", segs = { seg(-2, 2, 2, 2) } } }, nil))
  end)
  it("detects crossing your own older trail", function()
    local s = Geom.tilePath("straight", 3, origin)
    assert_true(Geom.pathHitsTrails(s, { { owner = "Red", segs = { seg(-2, 2, 2, 2) } } }, { x = 0, z = 0 }))
  end)
  it("a distant trail is not hit", function()
    local s = Geom.tilePath("straight", 3, origin)
    assert_false(Geom.pathHitsTrails(s, { { owner = "Blue", segs = { seg(5, 5, 6, 6) } } }, nil))
  end)
  it("another trail touching the joint point still counts as a hit", function()
    -- joint exemption only applies to a pair that BOTH end at the joint; a
    -- different trail passing through the joint on a non-endpoint is a crash
    local s = Geom.tilePath("straight", 3, origin)
    local through = { seg(-1, 0, 1, 0) }
    assert_true(Geom.pathHitsTrails(s, { { owner = "Blue", segs = through } }, { x = 0, z = 0 }))
  end)
end)

describe("Geom.pathCrossesPrizm", function()
  local prizm = seg(-1, 2, 1, 2)
  it("path straight through the Prizm captures it", function()
    local s = Geom.tilePath("straight", 3, { x = 0, z = 0, heading = 0 })
    assert_true(Geom.pathCrossesPrizm(s, prizm))
  end)
  it("path ending mid-Prizm does not capture", function()
    local s = Geom.tilePath("straight", 2, { x = 0, z = 0, heading = 0 })
    local endAt = seg(-1, Config.tiles[2].straight, 1, Config.tiles[2].straight)
    assert_false(Geom.pathCrossesPrizm(s, endAt))
  end)
  it("path stopping short does not capture", function()
    local s = Geom.tilePath("straight", 1, { x = 0, z = 0, heading = 0 })
    assert_false(Geom.pathCrossesPrizm(s, seg(-1, 10, 1, 10)))
  end)
  it("path crossing the axis line outside the Prizm span does not capture", function()
    local s = Geom.tilePath("straight", 3, { x = 5, z = 0, heading = 0 })
    assert_false(Geom.pathCrossesPrizm(s, prizm))
  end)
  it("path running alongside the Prizm does not capture", function()
    local s = Geom.tilePath("straight", 3, { x = 0.5, z = 0, heading = 0 })
    assert_false(Geom.pathCrossesPrizm(s, seg(0, 0, 0, 0.5)))
  end)
  it("an arc crossing the Prizm captures it", function()
    local s = Geom.tilePath("right", 3, { x = -1, z = 0, heading = 0 })
    assert_true(Geom.pathCrossesPrizm(s, seg(0, -1, 0, 5)))
  end)
  it("crossing exactly through a polyline vertex still captures", function()
    local through = { seg(0, 0, 1, 1), seg(1, 1, 2, 2) }
    assert_true(Geom.pathCrossesPrizm(through, seg(0, 1, 2, 1)))
  end)
  it("touching the axis at a vertex without crossing does not capture", function()
    local apex = { seg(0, 0, 1, 1), seg(1, 1, 2, 0) }
    assert_false(Geom.pathCrossesPrizm(apex, seg(0, 1, 2, 1)))
  end)
end)

describe("Geom.inBounds", function()
  local mat = { width = 36, depth = 36 }
  it("path inside the mat is in bounds", function()
    assert_true(Geom.inBounds({ seg(0, 0, 5, 5) }, mat))
  end)
  it("path leaving the mat is out of bounds", function()
    assert_false(Geom.inBounds({ seg(0, 0, 0, 20) }, mat))
    assert_false(Geom.inBounds({ seg(-19, 0, 0, 0) }, mat))
  end)
  it("exactly on the edge is in bounds", function()
    assert_true(Geom.inBounds({ seg(0, 0, 18, 18) }, mat))
  end)
end)

describe("Geom.tilePath non-zero headings", function()
  it("left curve from heading 90 bends toward +z and ends at heading 45", function()
    local _, e = Geom.tilePath("left", 3, { x = 0, z = 0, heading = 90 })
    assert_true(e.x > 0 and e.z > 0)
    assert_near(e.heading, 90 - Config.tiles[3].soft.sweep)
  end)
  it("right curve from heading 315 wraps heading to 0", function()
    local _, e = Geom.tilePath("right", 3, { x = 0, z = 0, heading = 315 })
    assert_near(e.heading, 0)
  end)
  it("left curve from heading 180 bends toward +x", function()
    local _, e = Geom.tilePath("left", 3, { x = 0, z = 0, heading = 180 })
    assert_true(e.x > 0 and e.z < 0)
  end)
end)

describe("Geom.segmentPose", function()
  it("+z segment has heading 0, +x segment heading 90", function()
    local p = Geom.segmentPose(seg(0, 0, 0, 4))
    assert_near(p.heading, 0); assert_near(p.length, 4); assert_near(p.z, 2)
    assert_near(Geom.segmentPose(seg(0, 0, 3, 0)).heading, 90)
  end)
  it("-z segment has heading 180 and -x heading 270", function()
    assert_near(Geom.segmentPose(seg(0, 0, 0, -1)).heading, 180)
    assert_near(Geom.segmentPose(seg(0, 0, -1, 0)).heading, 270)
  end)
  it("agrees with tilePath exit heading for a straight", function()
    local s, e = Geom.tilePath("straight", 2, { x = 0, z = 0, heading = 135 })
    assert_near(Geom.segmentPose(s[1]).heading, e.heading, 1e-6)
  end)
end)

describe("Geom tile helpers", function()
  it("tileChord of a straight equals its length", function()
    assert_near(Geom.tileChord("straight", 3), Config.tiles[3].straight)
  end)
  it("tileChord of a curve is shorter than its arc", function()
    local t = Config.tiles[3].soft
    local arc = t.radius * t.sweep * math.pi / 180
    assert_true(Geom.tileChord("left", 3) < arc)
    assert_near(Geom.tileChord("left", 3), Geom.tileChord("right", 3))
  end)
  it("tileCenter is halfway along a straight, in the heading direction", function()
    local c = Geom.tileCenter("straight", 2, { x = 1, z = 1, heading = 90 })
    assert_near(c.x, 1 + Config.tiles[2].straight / 2)
    assert_near(c.z, 1)
  end)
  it("distance is euclidean", function()
    assert_near(Geom.distance({ x = 0, z = 0 }, { x = 3, z = 4 }), 5)
  end)
end)

describe("Geom.bikeSeg", function()
  it("at a launch the bike stands just ahead of the pose, tail on it", function()
    local seg = Geom.bikeSeg({ x = 1, z = 2, heading = 0 }, true)
    assert_near(seg.a.x, 1); assert_near(seg.a.z, 2)
    assert_near(seg.b.x, 1); assert_near(seg.b.z, 2 + Config.bikeLength)
    seg = Geom.bikeSeg({ x = 0, z = 0, heading = 90 }, true)
    assert_near(seg.b.x, Config.bikeLength); assert_near(seg.b.z, 0, 1e-9)
  end)
  it("runs from the tail to the nose, nose on the pose", function()
    local seg = Geom.bikeSeg({ x = 1, z = 2, heading = 0 })
    assert_near(seg.b.x, 1); assert_near(seg.b.z, 2)
    assert_near(seg.a.x, 1); assert_near(seg.a.z, 2 - Config.bikeLength)
    seg = Geom.bikeSeg({ x = 0, z = 0, heading = 90 })
    assert_near(seg.a.x, -Config.bikeLength); assert_near(seg.a.z, 0, 1e-9)
  end)
end)

describe("curve shapes", function()
  it("a hard curve turns by its own sweep and is tighter than the soft one", function()
    local _, soft = Geom.tilePath("right", 3, { x = 0, z = 0, heading = 0 }, "soft")
    local _, hard = Geom.tilePath("right", 3, { x = 0, z = 0, heading = 0 }, "hard")
    assert_near(soft.heading, Config.tiles[3].soft.sweep)
    assert_near(hard.heading, Config.tiles[3].hard.sweep)
    assert_true(hard.heading > soft.heading)
    assert_true(hard.x > 0 and hard.z > 0)
  end)
  it("curves default to soft, and a missing shape is an error", function()
    local _, a = Geom.tilePath("left", 2, { x = 0, z = 0, heading = 0 })
    local _, b = Geom.tilePath("left", 2, { x = 0, z = 0, heading = 0 }, "soft")
    assert_near(a.x, b.x)
    local ok = pcall(Geom.tilePath, "left", 5, { x = 0, z = 0, heading = 0 }, "soft")
    assert_false(ok, "gear 5 has no curves")
    ok = pcall(Geom.tilePath, "left", 4, { x = 0, z = 0, heading = 0 }, "hard")
    assert_false(ok, "gear 4 has no hard curve")
  end)
end)
